# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('intid', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=128)),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('directory', models.CharField(max_length=256)),
                ('filename', models.CharField(max_length=20)),
                ('filesize', models.BigIntegerField(blank=True, default=0)),
                ('duration', models.SmallIntegerField(blank=True, default=0)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('subtitle', models.TextField(blank=True, default='')),
                ('channel_id', models.CharField(max_length=4)),
                ('channel_number', models.SmallIntegerField()),
                ('channel_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'orphans',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='orphan',
            unique_together=set([('hostname', 'filename')]),
        ),
    ]
